---

- name: restart sshd
  service: name=sshd state=restarted

- name: restart auditd
  service: name=auditd state=restarted

- name: restart syslog
  service: name=syslog state=restarted

- name: restart ntp
  service: name=ntpd state=restarted

- name: restart vami
  service: name=vami-lighttp state=restarted

- name: restart vpostgres
  shell: vmon-cli --restart vmware-vpostgres

- name: reload vpostgres config
  shell: /opt/vmware/vpostgres/current/bin/psql -U postgres -c "SELECT pg_reload_conf();"